name: Node.js CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '!v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Format check
        run: yarn format-check
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
